=== heenasalim/Java_Script/Simplehtmldemo/WebContent/WEB-INF/Dtdfile.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT Web ((GOOGLE,GMAIL,FB)+)>
<!ELEMENT GOOGLE (TWITTER,GAMES,JAVATPOINT,FLIPCART,SNAPDEAL)>
<!ELEMENT GMAIL (INBOX,COMPOSEMAIL,TRASH,SPAM)>
<!ELEMENT  TWITTER (#PCDATA)>
<!ELEMENT  GAMES (#PCDATA)>
<!ELEMENT JAVATPOINT (#PCDATA)>
<!ELEMENT  FLIPCART (#PCDATA)>
<!ELEMENT SNAPDEAL (#PCDATA)>
<!ELEMENT INBOX (#PCDATA)>
<!ELEMENT COMPOSEMAIL (#PCDATA)>
<!ELEMENT  TRASH (#PCDATA)>
<!ELEMENT SPAM (#PCDATA)>
<!ELEMENT FB (HOME,PROFILE,MESSAGE,LOGIN)>
<!ELEMENT HOME (#PCDATA)>
<!ELEMENT  PROFILE (#PCDATA)>
<!ELEMENT MESSAGE (#PCDATA)>
<!ELEMENT LOGIN (#PCDATA)>

=== heenasalim/Java_Script/Simplehtmldemo/WebContent/WEB-INF/XMLFORDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Web SYSTEM "Dtdfile.dtd" >
<Web>
  <GOOGLE>
    <TWITTER>TWITTER</TWITTER>
    <GAMES>GAMES</GAMES>
    <JAVATPOINT>JAVATPOINT</JAVATPOINT>
    <FLIPCART>FLIPCART</FLIPCART>
    <SNAPDEAL>SNAPDEAL</SNAPDEAL>
  </GOOGLE>
  <GMAIL>
    <INBOX>INBOX</INBOX>
    <COMPOSEMAIL>COMPOSEMAIL</COMPOSEMAIL>
    <TRASH>TRASH</TRASH>
    <SPAM>SPAM</SPAM>
  </GMAIL>
  <FB>
    <HOME>HOME</HOME>
    <PROFILE>PROFILE</PROFILE>
    <MESSAGE>MESSAGE</MESSAGE>
    "WebContent/WEB-INF/XMLFORDTD.xml"<LOGIN>LOGIN</LOGIN>
  </FB>
</Web>
