=== heenasalim/Java_Script/Simplehtmldemo/WebContent/WEB-INF/ExternalDtd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Vehicle ((bike,car)+)>
<!ELEMENT  bike (pept,activa,motor)>
<!ELEMENT car (Karisma,brut,Mahindra)>
<!ELEMENT pept (#PCDATA)>
<!ELEMENT activa (#PCDATA)>
<!ELEMENT pept (#PCDATA)>
<!ELEMENT motor (#PCDATA)>
<!ELEMENT Karisma (#PCDATA)>
<!ELEMENT brut (#PCDATA)>
<!ELEMENT Mahindra (#PCDATA)>

=== heenasalim/Java_Script/Simplehtmldemo/WebContent/WEB-INF/xmlFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Vehicle SYSTEM  "ExternalDtd.dtd" >
<Vehicle>
<bike>
<pept> This  is  scooty  pept</pept>
<activa> This  is  activa </activa>
<motor>This  is  motor </motor>
</bike>
<car>
<Karisma>Karisma</Karisma>
<brut>brut</brut>
<Mahindra>Mahindra</Mahindra>
</car>


</Vehicle>
<!--!DOCTYPE Vehicle PUBLIC "\\C:\\Users\\Lenovo\\Desktop\\JAVASCRIPT\\Simplehtmldemo\\WebContents\\ExternalDtdforxmlFile.dtd" "ExternalDtdforxmlFile.dtd"-->
